[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lagrange_interpolation"
version = "0.1.0"
description = "A library for Lagrange interpolation and visualization"
readme = "README.org"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
dependencies = [
    "numpy",
    "matplotlib"
]

[project.urls]
"Homepage" = "https://github.com/seajoyer/SupCo/tree/master/Lagrange_interpolation"
